version: "3"
services:
  db:
    image: postgres:15.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
  web:
    image: nginx:1.25.1-alpine
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/teamgenik.conf
    ports:
      - "80:80"
  app:
    build: .
    command: >
      elixir --cookie tg --sname tg@app
      --erl "-kernel inet_dist_listen_min 6000 inet_dist_listen_max 6100" -S mix phx.server
    volumes:
      - .:/app:cached
      - uploads:/app/uploads
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
    environment:
      - BLUEPRINT_SECRET_TOKEN
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - USE_GCS=${USE_GCS:-0}
volumes:
  uploads:
